package com.dao;

import java.sql.*;
import java.time.LocalDate;
import java.util.*;
import com.model.FeePayment;

public class FeePaymentDAO {

    private Connection con;

    public Connection getConnection() throws Exception {
        Class.forName("com.mysql.cj.jdbc.Driver");
        con = DriverManager.getConnection(
            "jdbc:mysql://localhost:3306/college_fee_db?useSSL=false&serverTimezone=UTC", 
            "root", 
            "ak@12345");
        return con;
    }

    // Get next Student ID (MAX StudentID + 1)
    public int getNextStudentId() throws Exception {
        String sql = "SELECT IFNULL(MAX(StudentID), 1000) + 1 FROM FeePayments";
        Connection con = getConnection();
        PreparedStatement ps = con.prepareStatement(sql);
        ResultSet rs = ps.executeQuery();
        int nextId = 1001;
        if(rs.next()) {
            nextId = rs.getInt(1);
        }
        rs.close();
        ps.close();
        con.close();
        return nextId;
    }
    
    // Get next Payment ID (for display - from trigger calculation)
    public int getNextPaymentId() throws Exception {
        String sql = "SELECT IFNULL(MAX(PaymentID), 0) + 1 FROM FeePayments";
        Connection con = getConnection();
        PreparedStatement ps = con.prepareStatement(sql);
        ResultSet rs = ps.executeQuery();
        int nextId = 1;
        if(rs.next()) {
            nextId = rs.getInt(1);
        }
        rs.close();
        ps.close();
        con.close();
        return nextId;
    }
    
    public String add(FeePayment f) throws Exception {
        StringBuilder errors = new StringBuilder();
        
        if (f.getStudentName() == null || f.getStudentName().trim().isEmpty()) {
            errors.append("Student name is required. ");
        } else if (!f.getStudentName().matches("^[A-Za-z\\s]{2,50}$")) {
            errors.append("Student name must be 2-50 characters. ");
        }
        
        if (f.getDepartment() == null || f.getDepartment().trim().isEmpty()) {
            errors.append("Department is required. ");
        }
        
        if (f.getAmount() < 100 || f.getAmount() > 500000) {
            errors.append("Amount must be between ₹100 and ₹500,000. ");
        }
        
        if (errors.length() > 0) {
            return errors.toString();
        }
        
        // Insert without PaymentID and StudentID - both will be auto-generated
        // StudentID by AUTO_INCREMENT, PaymentID by TRIGGER
        String sql = "INSERT INTO FeePayments(StudentName, Department, PaymentDate, Amount, Status) VALUES (?,?,?,?,?)";
        Connection con = getConnection();
        PreparedStatement ps = con.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS);
        
        ps.setString(1, f.getStudentName().trim());
        ps.setString(2, f.getDepartment().trim());
        ps.setDate(3, java.sql.Date.valueOf(LocalDate.now().toString()));
        ps.setDouble(4, f.getAmount());
        ps.setString(5, f.getStatus() != null ? f.getStatus() : "Pending");
        
        int result = ps.executeUpdate();
        
        // Get generated StudentID
        int generatedStudentId = 0;
        int generatedPaymentId = 0;
        ResultSet generatedKeys = ps.getGeneratedKeys();
        if (generatedKeys.next()) {
            generatedStudentId = generatedKeys.getInt(1);
        }
        generatedKeys.close();
        
        // Get the PaymentID that was generated by trigger
        PreparedStatement ps2 = con.prepareStatement("SELECT PaymentID FROM FeePayments WHERE StudentID = ?");
        ps2.setInt(1, generatedStudentId);
        ResultSet rs2 = ps2.executeQuery();
        if (rs2.next()) {
            generatedPaymentId = rs2.getInt("PaymentID");
        }
        rs2.close();
        ps2.close();
        
        ps.close();
        con.close();
        
        return result > 0 ? "SUCCESS: Payment Added! Payment ID: " + generatedPaymentId + " | Student ID: " + generatedStudentId : "ERROR: Failed to add payment.";
    }
    
    public String updateWithAllFields(int studentId, String studentName, String department, String paymentDate, double amount, String status) throws Exception {
        String checkSql = "SELECT COUNT(*) FROM FeePayments WHERE StudentID=?";
        Connection con = getConnection();
        PreparedStatement checkPs = con.prepareStatement(checkSql);
        checkPs.setInt(1, studentId);
        ResultSet rs = checkPs.executeQuery();
        rs.next();
        int count = rs.getInt(1);
        rs.close();
        checkPs.close();
        
        if (count == 0) {
            con.close();
            return "ERROR: No student found with ID: " + studentId;
        }
        
        String sql = "UPDATE FeePayments SET StudentName=?, Department=?, PaymentDate=?, Amount=?, Status=? WHERE StudentID=?";
        PreparedStatement ps = con.prepareStatement(sql);
        ps.setString(1, studentName);
        ps.setString(2, department);
        ps.setDate(3, java.sql.Date.valueOf(paymentDate));
        ps.setDouble(4, amount);
        ps.setString(5, status);
        ps.setInt(6, studentId);
        
        int result = ps.executeUpdate();
        
        ps.close();
        con.close();
        
        return result > 0 ? "SUCCESS: Payment updated successfully!" : "ERROR: Failed to update payment.";
    }

    public String delete(int studentId) throws Exception {
        if (studentId <= 0) {
            return "ERROR: Valid Student ID is required for deletion.";
        }
        
        String checkSql = "SELECT COUNT(*) FROM FeePayments WHERE StudentID=?";
        Connection con = getConnection();
        PreparedStatement checkPs = con.prepareStatement(checkSql);
        checkPs.setInt(1, studentId);
        ResultSet rs = checkPs.executeQuery();
        rs.next();
        int count = rs.getInt(1);
        rs.close();
        checkPs.close();
        
        if (count == 0) {
            con.close();
            return "ERROR: No student found with ID: " + studentId;
        }
        
        String sql = "DELETE FROM FeePayments WHERE StudentID=?";
        PreparedStatement ps = con.prepareStatement(sql);
        ps.setInt(1, studentId);
        
        int result = ps.executeUpdate();
        
        ps.close();
        con.close();
        
        return result > 0 ? "SUCCESS: Payment record deleted successfully!" : "ERROR: Failed to delete payment.";
    }

    public List<FeePayment> searchByName(String name) throws Exception {
        List<FeePayment> list = new ArrayList<>();
        
        if (name == null || name.trim().isEmpty()) {
            return list;
        }
        
        String searchTerm = name.trim();
        String sql = "SELECT * FROM FeePayments WHERE StudentName LIKE ? ORDER BY StudentID ASC";
        
        Connection con = getConnection();
        PreparedStatement ps = con.prepareStatement(sql);
        ps.setString(1, "%" + searchTerm + "%");
        
        ResultSet rs = ps.executeQuery();
        
        while(rs.next()){
            FeePayment f = new FeePayment();
            f.setStudentId(rs.getInt("StudentID"));
            f.setPaymentId(rs.getInt("PaymentID"));
            f.setStudentName(rs.getString("StudentName"));
            f.setDepartment(rs.getString("Department"));
            f.setPaymentDate(rs.getString("PaymentDate"));
            f.setAmount(rs.getDouble("Amount"));
            f.setStatus(rs.getString("Status"));
            list.add(f);
        }
        
        rs.close();
        ps.close();
        con.close();
        
        return list;
    }

    public double getTotalCollection() throws Exception {
        double total = 0;
        String sql = "SELECT COALESCE(SUM(Amount), 0) FROM FeePayments WHERE Status = 'Paid'";
        
        Connection con = getConnection();
        PreparedStatement ps = con.prepareStatement(sql);
        ResultSet rs = ps.executeQuery();
        
        if(rs.next()){
            total = rs.getDouble(1);
        }
        
        rs.close();
        ps.close();
        con.close();
        
        return total;
    }
    
    public double getPendingAmount() throws Exception {
        double total = 0;
        String sql = "SELECT COALESCE(SUM(Amount), 0) FROM FeePayments WHERE Status = 'Pending'";
        
        Connection con = getConnection();
        PreparedStatement ps = con.prepareStatement(sql);
        ResultSet rs = ps.executeQuery();
        
        if(rs.next()){
            total = rs.getDouble(1);
        }
        
        rs.close();
        ps.close();
        con.close();
        
        return total;
    }

    public List<FeePayment> getAll() throws Exception {
        List<FeePayment> list = new ArrayList<>();
        String sql = "SELECT * FROM FeePayments ORDER BY StudentID ASC";
        
        Connection con = getConnection();
        PreparedStatement ps = con.prepareStatement(sql);
        ResultSet rs = ps.executeQuery();
        
        while(rs.next()){
            FeePayment f = new FeePayment();
            f.setStudentId(rs.getInt("StudentID"));
            f.setPaymentId(rs.getInt("PaymentID"));
            f.setStudentName(rs.getString("StudentName"));
            f.setDepartment(rs.getString("Department"));
            f.setPaymentDate(rs.getString("PaymentDate"));
            f.setAmount(rs.getDouble("Amount"));
            f.setStatus(rs.getString("Status"));
            list.add(f);
        }
        
        rs.close();
        ps.close();
        con.close();
        
        return list;
    }
    
    public FeePayment getPaymentByStudentId(int studentId) throws Exception {
        String sql = "SELECT * FROM FeePayments WHERE StudentID=?";
        
        Connection con = getConnection();
        PreparedStatement ps = con.prepareStatement(sql);
        ps.setInt(1, studentId);
        ResultSet rs = ps.executeQuery();
        
        if(rs.next()){
            FeePayment f = new FeePayment();
            f.setStudentId(rs.getInt("StudentID"));
            f.setPaymentId(rs.getInt("PaymentID"));
            f.setStudentName(rs.getString("StudentName"));
            f.setDepartment(rs.getString("Department"));
            f.setPaymentDate(rs.getString("PaymentDate"));
            f.setAmount(rs.getDouble("Amount"));
            f.setStatus(rs.getString("Status"));
            
            rs.close();
            ps.close();
            con.close();
            return f;
        }
        
        rs.close();
        ps.close();
        con.close();
        return null;
    }
    
    // Get statistics by department
    public Map<String, Double> getCollectionByDepartment() throws Exception {
        Map<String, Double> deptStats = new HashMap<>();
        String sql = "SELECT Department, SUM(Amount) as Total FROM FeePayments WHERE Status = 'Paid' GROUP BY Department";
        
        Connection con = getConnection();
        PreparedStatement ps = con.prepareStatement(sql);
        ResultSet rs = ps.executeQuery();
        
        while(rs.next()){
            deptStats.put(rs.getString("Department"), rs.getDouble("Total"));
        }
        
        rs.close();
        ps.close();
        con.close();
        
        return deptStats;
    }
}